---
title: "Codebook"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: true
  pdf_document:
    toc: yes
    toc_depth: 4
    latex_engine: xelatex
---


```{r setup}
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually better for debugging
  echo = TRUE  # show R code
)
ggplot2::theme_set(ggplot2::theme_bw())
pander::panderOptions("table.split.table", Inf)
```

```{r libraries, include=FALSE}

library(codebook)
library(tidyverse)
library(labelled)

```


```{r}
knit_by_pkgdown <- !is.null(knitr::opts_chunk$get("fig.retina"))
pander::panderOptions("table.split.table", Inf)
ggplot2::theme_set(ggplot2::theme_bw())
knitr::opts_chunk$set(warning = TRUE, message = TRUE, error = TRUE, echo = TRUE)

ptsd <- rio::import("https://osf.io/uv7fm/download", "sav")

```


```{r prepare_codebook}


codebook_data <- ptsd

# 
# var_label(codebook_data) <- dict %>% select(Variable, Label) %>% dict_to_list()

# omit the following lines, if your missing values are already properly labelled
codebook_data <- detect_missing(codebook_data,
    only_labelled = TRUE, # only labelled values are autodetected as
                                   # missing
    negative_values_are_missing = FALSE, # negative values are missing values
    ninety_nine_problems = TRUE,   # 99/999 are missing values, if they
                                   # are more than 5 MAD from the median
    )

# If you are not using formr, the codebook package needs to guess which items
# form a scale. The following line finds item aggregates with names like this:
# scale = scale_1 + scale_2R + scale_3R
# identifying these aggregates allows the codebook function to
# automatically compute reliabilities.
# However, it will not reverse items automatically.
codebook_data <- detect_scales(codebook_data)
```


```{r}
metadata(codebook_data)$name <- "
Current Posttraumatic Stress Disorder symptomatology distorts memory for past symptoms
"

metadata(codebook_data)$description <- paste0("


### Download link
[Open Science Framework]https://osf.io/uv7fm/download)

")


metadata(codebook_data)$identifier <- "https://osf.io/bdax7/"
metadata(codebook_data)$datePublished <- "2018-05-04"
metadata(codebook_data)$contributors <- list(
      " Sasha Nahleen"," Reginald Nixon ", "Melanie Takarangi")

metadata(codebook_data)$url <- "https://osf.io/uv7fm/"
metadata(codebook_data)$temporalCoverage <- "2018" 

metadata(codebook_data)$distribution = list(
  list("@type" = "DataDownload",
       "requiresSubscription" = "http://schema.org/True",
       "encodingFormat" = "https://www.loc.gov/preservation/digital/formats/fdd/fdd000469.shtml",
       contentUrl = "https://osf.io/uv7fm/download")
)
```



```{r codebook}
codebook(codebook_data)
```
